# Generated by Django 4.2.4 on 2023-08-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_create_group_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(blank=True, to='mentorship.student'),
        ),
    ]
